/* Auto-generated by doc2code — do not edit by hand */

export interface LMStreamParams {
  text: string;
  caret: number;
  active_region: { start: number; end: number };
  settings?: Record<string, unknown>;
}
