# MindType macOS App — XcodeGen Configuration
# Run: xcodegen generate

name: MindTypeApp
options:
  bundleIdPrefix: com.mindtype
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    MARKETING_VERSION: "0.9.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  MindTypeApp:
    type: application
    platform: macOS
    sources:
      - path: MindTypeApp
        excludes:
          - "*.xcodeproj"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mindtype.app
        INFOPLIST_FILE: MindTypeApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: MindTypeApp/MindTypeApp.entitlements
        PRODUCT_NAME: MindType
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: MindTypeApp/MindTypeApp.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
    info:
      path: MindTypeApp/Info.plist
      properties:
        CFBundleDisplayName: MindType
        CFBundleName: MindType
        CFBundleIdentifier: com.mindtype.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "0.9.0"
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true  # Menu bar app
        NSHumanReadableCopyright: "Copyright © 2025 MindType"

